// export const GET_LIST_COURSE_START = 'GET_LIST_COURSE_START';
export const GET_LIST_COURSE = 'GET_LIST_COURSE';
// export const GET_LIST_COURSE_FAILURE = 'GET_LIST_COURSE_FAILURE';

export const DELETE_LIST_COURSE = 'DELETE_LIST_COURSE';
export const ADD_COURSE = 'ADD_COURSE';
